spring:
  #需要被zipkin链路追踪
  zipkin:
    base-url: http://localhost:9411
  application:
    name: ribbon
#  thymeleaf:
#    cache: false
#    mode: LEGACYHTML5
#    encoding: UTF-8
#    servlet:
#      content-type: text/html

server:
  port: 8763

eureka:
  client:
    serviceUrl:
      defaultZone: http://server1:8861/eureka/,http://server2:8761/eureka/,http://server3:8961/eureka/