spring:
  application:
    name: server-admin
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8084  #默认端口号

# admin配置
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info

eureka:
  client:
    serviceUrl:
      defaultZone: http://server1:8761/eureka/,http://server2:8861/eureka/,http://server3:8961/eureka/