spring:
  application:
    name: serviceprovider-hello
  #需要被zipkin链路追踪
  zipkin:
    base-url: http://localhost:9411
  #需要被admin监控
  boot:
    admin:
      client:
        url: http://localhost:8084

#server:
#  port: 8762

eureka:
  client:
    serviceUrl:
      defaultZone: http://server1:8861/eureka/,http://server2:8761/eureka/,http://server3:8961/eureka/